apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-demo
  namespace: devsecops
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate: {maxUnavailable: 0, maxSurge: 1}
  selector:
    matchLabels: {app: devsecops-demo}
  template:
    metadata:
      labels: {app: devsecops-demo}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: app
          image: ghcr.io/not-so-shubh/devsecops-demo:latest
          ports: [{name: http, containerPort: 8080}]
          readinessProbe: {httpGet: {path: /ready, port: http}, periodSeconds: 5}
          livenessProbe: {httpGet: {path: /health, port: http}, periodSeconds: 10}
          resources:
            requests: {cpu: 20m, memory: 32Mi}
            limits: {cpu: 200m, memory: 128Mi}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: ["ALL"]}
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-demo
  namespace: devsecops
spec:
  selector: {app: devsecops-demo}
  ports: [{name: http, port: 80, targetPort: http}]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: devsecops
spec:
  podSelector: {}
  policyTypes: ["Ingress", "Egress"]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-app
  namespace: devsecops
spec:
  podSelector:
    matchLabels: {app: devsecops-demo}
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - ports: [{protocol: TCP, port: 8080}]
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
