apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-web.fullname" . }}
  labels:
    {{- include "devops-web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "devops-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devops-web.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          ports:
            - name: http
              containerPort: 8080
          command: ["/bin/sh", "-c"]
          args:
            - nginx -c /tmp/nginx.conf -g 'daemon off;'
          readinessProbe:
            httpGet: {path: /, port: http}
            periodSeconds: 5
          livenessProbe:
            httpGet: {path: /, port: http}
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: content
              mountPath: /usr/share/nginx/html
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
            - name: nginx-config
              mountPath: /tmp/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: content
          configMap:
            name: {{ include "devops-web.fullname" . }}
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: {{ include "devops-web.fullname" . }}-nginx
