apiVersion: v1
kind: Service
metadata:
  name: identity-stateful
spec:
  clusterIP: None
  selector:
    app: identity-stateful
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: identity-stateful
spec:
  serviceName: identity-stateful
  replicas: 2
  selector:
    matchLabels:
      app: identity-stateful
  template:
    metadata:
      labels:
        app: identity-stateful
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
