apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
        - name: node-agent
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              while true; do
                echo "node agent alive on $(hostname)"
                sleep 30
              done
