apiVersion: v1
kind: Pod
metadata:
  name: pending-demo
  namespace: session14
spec:
  containers:
    - name: app
      image: nginx:1.27-alpine
      resources:
        requests:
          cpu: "100"
          memory: 100Gi
