apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-tracker-backend
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: ["final-devops"]
  selector:
    matchLabels: {app: release-tracker-backend}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
