apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      slot: blue
  template:
    metadata:
      labels:
        app: myapp
        slot: blue
    spec:
      containers:
        - name: app
          image: busybox:1.36
          command: ["sh", "-c", "mkdir -p /www; echo '<p>BLUE ENVIRONMENT</p>' > /www/index.html; httpd -f -p 8080 -h /www"]
          ports:
            - containerPort: 8080
